### ISSUE TITLE
Consider moving away from rustc-cfg?

### ISSUE THREAD

**Issue by brightly-salty** [rust-embedded/cargo-binutils#100]
It looks like rustc-cfg is unmaintained or at least dormant. There are no commits since October 2018, and it's dependence on failure (despite a PR to fix it) makes `cargo-audit` fail for cargo-binutils and anything that depends on it. 

It might be better to move this functionality into cargo-binutils itself. rustc-cfg/src/lib.rs contains less than 200 lines of code, many of which are comments. If the licenses are compatible, I think it would be beneficial to move this file/code into cargo-binutils so it can continue to receive maintenance and updates.

**Comment by therealprof** [comment]
Fair enough. @japaric who's both the original author of the dependency in question and `cargo-binutils` might have an opinion on how we could proceed here.

**Comment by japaric** [comment]
Importing rustc-cfg code into this repo seems fine to me. I think there's another crate that does about the same as rustc-cfg but I can't remember the name right now.

**Comment by Emilgardis** [comment]
rustc-cfg was updated in https://github.com/rust-embedded/cargo-binutils/pull/128
