### ISSUE TITLE
Utils nm, objdump, readobj: Incorrect help option in message "To see all the flags the proxied tool accepts..."

### ISSUE THREAD

**Issue by mirao** [rust-embedded/cargo-binutils#125]
```bash
$ cargo nm --help
..
The arguments specified *after* the `--` will be passed to the proxied tool invocation.

To see all the flags the proxied tool accepts run `cargo-nm -- -help`.
..
```
But if you try to use the offered command `cargo-nm -- -help`, it fails:
```bash
$ cargo-nm -- -help
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
/home/mirao/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-nm: error: : unknown argument '-e'
```
Correct syntax is `cargo-nm -- --help`.
I tried all `llvm-*` tools. Most of them accept `-help` and **all** of them accept `--help` as well.

So a solution might be to replace `-help` by `--help` here:
https://github.com/rust-embedded/cargo-binutils/blob/9f0a6ff71a66e34d7582e27e1c1459702df77465/src/lib.rs#L157

**Used SW:**

- Ubuntu 22.04
- cargo 1.62.0 (a748cf5a3 2022-06-08)
- cargo-binutils v0.3.6
- rustup component `llvm-tools-preview-x86_64-unknown-linux-gnu`

**Comment by Emilgardis** [comment]
This sounds good, feel free to make a pr for it!
