### ISSUE TITLE
Error linking with win11 on a bevy project

### ISSUE THREAD

**Issue by Paulo-21** [rust-embedded/cargo-binutils#129]
Hey, i got this error while compiling my [bevy](https://bevyengine.org/) project with rust-lld on windows 11 
I precise that it work perfectly on win10.
If you want to reproduce, [i link you my project](https://github.com/Paulo-21/bevy-learn)

Error : STATUS_STACK_BUFFER_OVERRUN

<img width="883" alt="image" src="https://user-images.githubusercontent.com/34631206/197357724-aad39977-ce1c-4f9b-b870-94b54f698d51.png">

**Comment by Emilgardis** [comment]
`cargo-binutils` does not do anything that would give this error

Found this which is the same issue on the same OS: https://github.com/rust-lang/rust/issues/100519

closing this issue
