### ISSUE TITLE
cargo size, total size?

### ISSUE THREAD

**Issue by tomasApo** [rust-embedded/cargo-binutils#130]
Quick question, 

How much flash memorry does my project take up? 

Running `cargo size` 
Total flash memory = text + data?
What does bbs mean?

![image](https://user-images.githubusercontent.com/75183079/209415375-5b11464b-a39a-4a08-88a5-11cffc19c510.png)

**Comment by Emilgardis** [comment]
text = flash, bss = uninitalized, data = initialized, dec = total

see https://docs.rust-embedded.org/book/start/qemu.html#inspecting

**Comment by tomasApo** [comment]
@Emilgardis Thank you
