### ISSUE TITLE
Cargo-size can't show fireware size on stm32g4

### ISSUE THREAD

**Issue by qff233** [rust-embedded/cargo-binutils#142]
I use example of embassy. When I run `cargo size`, it all show zero.
![image](https://github.com/rust-embedded/cargo-binutils/assets/31184456/325003a0-9984-4b1c-be3e-87965752b60b)
And when I run `cargo size -- -A`, it show that it don't have `.text` and `.data`.
![image](https://github.com/rust-embedded/cargo-binutils/assets/31184456/200f0037-5e24-40e8-84aa-1a7fb6e83ce9)

**Comment by burrbull** [comment]
It looks like rust target was not set.
