### ISSUE TITLE
use of unstable library feature | installation Error

### ISSUE THREAD

**Issue by sharma-shray** [rust-embedded/cargo-binutils#144]
cargo install cargo-binutils : 

error[E0658]: use of unstable library feature 'proc_macro_byte_character'
error[E0658]: use of unstable library feature 'proc_macro_c_str_literals'

**Comment by Emilgardis** [comment]
We don't use these features and they've recently been stabilized and expected for 1.79. Looking at https://github.com/rust-lang/rust/issues/115268 I see that other's are experiencing this.

Are you on nightly? If so, please update your nightly toolchain

**Comment by Emilgardis** [comment]
Closing this issue.
