### ISSUE TITLE
`cargo objcopy` with no arguments outputs incorrect (?) help message

### ISSUE THREAD

**Issue by ryankurte** [rust-embedded/cargo-binutils#36]
Calling `cargo-objcopy` appears to output llvm-objcopy help message instead of the cargo-objcopy help message, afaik this should should require `cargo objcopy -- -help`?

**Comment by ryankurte** [comment]
Or perhaps it should just do the right thing (tm) when no arguments are provided? For example, default behaviour of building the binary/binaries listed in Cargo.toml in --release mode and outputting .bin files?

**Comment by japaric** [comment]
Right now, invoking `cargo-$tool` is the same as invoking `path/to/llvm-$tool`. I think it's fine to change the semantics (to e.g. print the `cargo-$tool` help) since it's very likely that no one is using `cargo-$tool` (without passing any arguments).

**Comment by therealprof** [comment]
Should work just fine now and improve even more with #61. Closing thus.
