### ISSUE TITLE
rust-lld

### ISSUE THREAD

**Issue by daxpedda** [rust-embedded/cargo-binutils#47]
Currently `rust-lld` is exposed as `rust-ld`, is there any particular reason for this?

My use case:
I noticed some odd behaviour when compiling for wasm in combination with `-Z build-std`, it needed additional help with `-C linker-flavor=wasm-ld` because of the name change.

I already found a solution for my use case, so this is rather a question than anything else.

**Comment by therealprof** [comment]
Yes, the reason is `binutils` compatibility.
