### ISSUE TITLE
cargo size error: Can only have one matching artifact but found several

### ISSUE THREAD

**Issue by korken89** [rust-embedded/cargo-binutils#81]
Hi,

When running `cargo size --release` (cargo-binutils v0.3.0) on a fresh repository I get the following error:

```
error: Can only have one matching artifact but found several
```

However checking the `target` folders there is only one artifact (`app` in my case):

```
thumbv7em-none-eabihf/debug/deps/app-a3b7f7101f0da200.d
thumbv7em-none-eabihf/debug/deps/app-f6b81f508609ad5e.d
thumbv7em-none-eabihf/debug/deps/libapp-a3b7f7101f0da200.rmeta
thumbv7em-none-eabihf/debug/deps/libapp-f6b81f508609ad5e.rmeta
thumbv7em-none-eabihf/release/app
thumbv7em-none-eabihf/release/app.d
thumbv7em-none-eabihf/release/deps/app-1f4505e64d40502e.d
thumbv7em-none-eabihf/release/deps/app-8b955e72da6ee189
thumbv7em-none-eabihf/release/deps/app-8b955e72da6ee189.d
thumbv7em-none-eabihf/release/deps/libapp-1f4505e64d40502e.rlib
thumbv7em-none-eabihf/release/deps/libapp-1f4505e64d40502e.rmeta
thumbv7em-none-eabihf/release/libapp.d
thumbv7em-none-eabihf/release/libapp.rlib
```

What seems to be happening is that it does not realize it should look for the binary.
Running the following gives the expected result: `cargo size --release --bin app`
And I have the `[[bin]]` section in the Cargo.toml, which was working fine before (not sure which version of `cargo-binutils`).

**Comment by therealprof** [comment]
Hm... can't reproduce. Neither with nor without `[[bin]]`.

```
# cargo size --release
    Finished release [optimized + debuginfo] target(s) in 0.03s
   text	   data	    bss	    dec	    hex	filename
  15308	      0	      4	  15312	   3bd0	app
```

**Comment by korken89** [comment]
Weird it seems @thalesfragoso also had the same issue as me.
Not sure how to not make it happen, because for me it happens on all repositories now.

**Comment by therealprof** [comment]
Can you point to a public repo where this happens? Maybe there's a subtle difference in setup.

**Comment by DerFetzer** [comment]
I am having the same problem on one of my [repos](https://github.com/DerFetzer/open-cleverpad).
[Another one](https://github.com/DerFetzer/stm32-ccs811) is working fine.
I am using cargo-binutils v0.2.0.

**Comment by therealprof** [comment]
> I am using cargo-binutils v0.2.0.

And with 0.3.0?

**Comment by therealprof** [comment]
Hah! Found the problem. That darn `build.rs` causes an additional artifact of type "custom-build", that's why cargo complains about multiple artifacts.

**Comment by korken89** [comment]
Awesome job!

**Comment by therealprof** [comment]
That doesn't mean I have any idea how to properly fix it, yet. ;) Should we just ignore custom build artifacts? Not sure if people are not using that for real...
