### ISSUE TITLE
Support `--manifest-path` for specifying a project dir

### ISSUE THREAD

**Issue by ryankurte** [rust-embedded/cargo-binutils#95]
when building components of a larger project it is often useful to specify the manifest directory directly, particularly because we can't really do multi-target workspaces https://github.com/rust-lang/cargo/issues/7004.

relates to https://github.com/actions-rs/cargo/issues/86 which _could_ mitigate this problem for github-actions.

(also _seem_ to be seeing a similar issue to https://github.com/rust-lang/cargo/issues/4866 when trying to build `log` for the wrong target when using a workspace but, not sure why that is)

**Comment by PhilippMolitor** [comment]
currently experiencing the same issue.

**Comment by PhilippMolitor** [comment]
can be closed
